version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    rebase-strategy: auto
    schedule:
      interval: monthly
    versioning-strategy: increase
    labels:
      - dependencies
    open-pull-requests-limit: 15
    groups:
      production-dependencies:
        dependency-type: production
      typescript:
        patterns:
          - typescript
          - '@types/*'
        exclude-patterns:
          - '@types/eslint'
      docs:
        patterns:
          - 'astro'
          - '*astro*'
          - '@astrojs/*'
          - 'tailwindcss'
          - 'postcss'
          - 'netlify-*'
      eslint:
        patterns:
          - '*eslint*'
