name: oneRepo
description: Run oneRepo tasks on GitHub
inputs:
  packageManager:
    description: Package manager to use (`npm`, `yarn`, `pnpm`)
    required: true
  lifecycle:
    description: The lifecycle that will be run
    required: true
  overrideBin:
    description: Override the path to the `one` executable
  verbosity:
    description: How verbose to be

runs:
  using: node20
  main: ../../modules/github-action/dist/get-tasks.cjs
