name: oneRepo
description: Run oneRepo tasks on GitHub
inputs:
  task:
    description: A single task or sequence of tasks from the oneRepo tasks --list output
    required: true

runs:
  using: node20
  main: ../../modules/github-action/dist/run-task.cjs
